baseURL: "https://danielleitelima.com"
languageCode: "en-us"
title: "Daniel's profile"

Paginate: 3
disqusShortname: danielleitelima

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1

params:
  title: "Daniel's profile"
  # description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.svg"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hello,"
    title: "I'm Daniel"
    content: "A software engineer passionate about building better solutions and learning new technologies."
    image: /images/photo_1.jpeg
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/danielleitelima
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/daniel-leite-lima-2253531b6/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/photo_2.png"
    content: |-
      Senior Developer with solid experience in back-end and front-end applications, especially mobile. Passionate about learning new technologies and creating new and better solutions. I seek new professional challenges to enhance my skills and generate positive results in myself, in the corporate environment and in society.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "[Android](https://developer.android.com/)"
        - "[Android Jetpack](https://developer.android.com/jetpack)"
        - "[Flutter](https://flutter.dev/)"
        - "[Kotlin](https://kotlinlang.org/)"
        - "[Java Enterprise Edition](https://www.oracle.com/java/technologies/java-ee-glance.html)"
        - "[Linux](https://www.linux.org/)"
        - "[Spring](https://spring.io/)"
        - "[Firebase](https://firebase.google.com/)"
        - "[PostgreSQL](https://www.postgresql.org/)"
        - "[Javascript](https://www.javascript.com/)"
        - "[HTML](https://developer.mozilla.org/en-US/docs/Web/HTML)"
        - "[Git](https://git-scm.com/)"
        - "[Github Actions](https://github.com/features/actions)"
        - "[Hugo](https://gohugo.io/)"

  # Experience
  experience:
    enable: true
    items:
      - job: "Android Engineer"
        company: "MAYD - Meds At Your Doorstep"
        companyUrl: "https://www.getmayd.com/"
        date: "Jul 2021 - present"
        info:
          enable: false
        content: |
          MAYD is a successful startup with the goal of providing quickly delivered meds for users across Europe. As part of the Android team, I'm responsible for delivering new and exciting features and for guaranteeing software quality.

      - job: "Senior Android Developer"
        company: "BTG Pactual"
        companyUrl: "https://www.btgpactual.com/"
        date: "Oct 2020 - Jun 2021"
        info:
          enable: false
        content: |
          BTG Pactual is currently the largest investment bank in Latin America. I worked on one of the most important projects, the [banking app](https://play.google.com/store/apps/details?id=com.btg.pactual.banking). I and a big team of Android engineers, implemented challenging new functionalities to the app, giving the bank users an increasingly better experience. Also, we monitored closely the software quality to assure the satisfaction of most users.

      - job: "Senior Android Developer"
        company: "SSPDS"
        companyUrl: "https://www.sspds.ce.gov.br/"
        date: "Dez 2017 - May 2018"
        info:
          enable: false
        content: |
          I added very important new functionalities to the app used by selected police officers. The officer's phones needed to be traceable and provide patrol routes, calculated based on emergency reports given by the citizens.
      
      - job: "Full-stack Developer"
        company: "IPECE"
        companyUrl: "https://www.ipece.ce.gov.br/"
        date: "Nov 2017 - Feb 2018"
        info:
          enable: false
        content: |
          I implemented a complete solution to show the most recent researches and news of the company. The mobile app I designed was built in flutter, with native IOS and Android code and the back-end application was built using Java, enterprise edition.

      - job: "Full-stack Developer"
        company: "Nova Via"
        companyUrl: "https://novavia.net.br/"
        date: "Sep 2015 - Oct 2020"
        info:
          enable: false
        #   content: I worked as a software developer for more than one year in Amazon.
        # featuredLink:
        #   enable: true
        # name: "View the project"
        #   url: "https://novavia.net.br/"
        content: |
          Here I started my career as a developer. We developed technologies to supply the IT needs of police officers. Our app made it easy to register traffic violations, vehicle seizures, and traffic accidents. With the gathered data we helped the authorities diminish radically these events delivering precise reports and new functionalities on the app. I became the manager of this project and others in the same company.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Mathematics school"
        school:
          name: "Federal State University of Ceará, Fortaleza - Brazil"
          url: "https://www.ufc.br/"
        date: "2014 - 2020"
        content: |-
          Extracurricular Activities
            - As part of my scholarship duties, I worked on software solutions to be applyed in a public school, such as a web application to manage the books in the library.
            - Studied Graphs theory, as apprentice of an applied mathematics research group, called [ParGO](https://pargo.ufc.br/pt/apresentacao/).
      - title: "Analysis and systems development"
        school:
          name: "Estácio University, Curitiba - Brazil"
          url: "https://estacio.br/"
        date: "2019 - 2021"
      - title: "High School"
        school:
          name: "Maria Ester II"
          url: "https://colegiomariaester.com.br/"
        content: |-
          Extracurricular Activities
            - Joined the Brazilian Informatics Olympiad and achieved the 32⍛ national position.
        featuredLink:
          enable: true
          name: "Olympiad website"
          url: "https://olimpiada.ic.unicamp.br/"
  # Achievements
  achievements:
    enable: false

  # projects
  projects:
    enable: false

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: limaleite.daniel@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/danielleitelima
      linkedin: https://www.linkedin.com/in/daniel-leite-lima-2253531b6/